import "server-only";

export const RuntimeServerConfig = {
  useMockData: process.env.NEXT_PUBLIC_USE_MOCK_DATA !== "false",
  env: {
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    FROM_EMAIL: process.env.FROM_EMAIL,
    ADMIN_EMAIL: process.env.ADMIN_EMAIL,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    NODE_ENV: process.env.NODE_ENV,
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
    CRON_SECRET: process.env.CRON_SECRET,
    LEMONSQUEEZY_API_KEY: process.env.LEMONSQUEEZY_API_KEY,
    LEMONSQUEEZY_WEBHOOK_SECRET: process.env.LEMONSQUEEZY_WEBHOOK_SECRET,
    LEMONSQUEEZY_STARTER_CHECKOUT_URL:
      process.env.LEMONSQUEEZY_STARTER_CHECKOUT_URL,
    LEMONSQUEEZY_PRO_CHECKOUT_URL: process.env.LEMONSQUEEZY_PRO_CHECKOUT_URL,
    LEMONSQUEEZY_GROWTH_CHECKOUT_URL:
      process.env.LEMONSQUEEZY_GROWTH_CHECKOUT_URL,
    LEMONSQUEEZY_PORTAL_URL: process.env.LEMONSQUEEZY_PORTAL_URL,
  },
};
